name: Chore
description: A task to do
labels: ["chore", "triage"]
projects: ["MOTDgd-Ltd/1"]
assignees:
  - octocat
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe what the needs to be done
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance criteria
      description: What constitutes as done
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Any additional notes to help whoever picks this up
    validations:
      required: false
